### PR TITLE
netops: handle intact query parameters in service_suffix removal

### LINKED ISSUE #5321: /info/refs http request malformed when base remote path is /
### Reproduction steps

Construct an http git remote whose URL has path `/`, such as `http://localhost:8080/`. Do a push.

### Expected behavior

libgit2 sends an HTTP request with URL `/info/refs?service=git-receive-pack`. (This is what command line git does.)

### Actual behavior

libgit2 sends an HTTP request with URL `/info/refs?service=git-receive-pack/info/refs?service=git-receive-pack`.

### Version of libgit2 (release number or SHA1)

7acb764eeeea22cbfaa4dd625bc8516966ed96f3 (master at time of posting)

Remote URLs of this form also fail with v28, but for different reasons. (c6ab183e9c960b74471a7d106a4deb0c8b28a8ec, which postdates v28, fixed other bugs with such URLs.)

### OS

macOS

### PR DESCRIPTION
**Pull request by josharian**
Some servers leave the query parameters intact in the
Location header when responding with a redirect.
The service_suffix removal check as written assumed
that the server removed them.
Handle both cases.

Along with PR #5325, this fixes #5321.

Please review skeptically; my C is extremely rusty.

### CODE REVIEW

File: src/netops.c [hunk 1]
```diff
@@ -171,25 +171,41 @@ int gitno_connection_data_handle_redirect(
...
-				/* Ensure we leave a minimum of '/' as the path */
-				if (suffix_offset == 0)
-					suffix_offset++;
+				truncate = suffix_offset;
+			}
+		}
 
-				url->path[suffix_offset] = '\0';
+		/* Check for retained query parameters. */
+		if ((truncate == -1) && (git__suffixcmp(url->path, service_suffix) == 0)) {
```
Comment (pks-t) [inline src/netops.c]: We usually have no braces around comparisons

Comment (josharian) [reply src/netops.c]: Done

**Comment by josharian** [comment]
> I honestly find it very hard to reason about this, but this is no fault of yours.

That's kind, but I'll take the fault. I've added more documentation in the code.

> We do have tests in "tests/network/redirect.c" that are supposed to exercise this function. 

Thanks for the pointer. I hadn't found those, only the tests against live servers. I've added two tests. The first already passed; the second previously failed.
