### PR TITLE
Fix revwalk limiting regression

### LINKED ISSUE #4740: Performance regression in `revwalk` API
### Explanation

Atom uses libgit2's `revwalk` API to compute the number of commits by which the user's current branch is 'ahead' and 'behind' its corresponding remote branch. After upgrading from libgit2 0.24 to 0.26, we're seeing this code take a long time to execute, even when the branch is up-to-date with its remote (no commits ahead or behind).

### Reproduction steps

1. Clone the [Atom](https://github.com/atom/atom) repository

1. Create a C file called `test.c` with this content:

```c
#include "git2.h"
#include <stdio.h>
#include <assert.h>

unsigned count_commits_between_refs(
  git_repository *repo,
  const char *ref1,
  const char *ref2
) {
  git_oid oid1, oid2;
  assert(git_reference_name_to_id(&oid1, repo, ref1) == GIT_OK);
  assert(git_reference_name_to_id(&oid2, repo, ref2) == GIT_OK);

  git_oid merge_base;
  assert(git_merge_base(&merge_base, repo, &oid1, &oid2) == GIT_OK);

  git_revwalk *revwalk;
  assert(git_revwalk_new(&revwalk, repo) == GIT_OK);

  git_revwalk_push(revwalk, &oid1);
  git_revwalk_hide(revwalk, &oid2);

  unsigned result = 0;
  git_oid current_commit;
  while (git_revwalk_next(&current_commit, revwalk) == GIT_OK) result++;
  git_revwalk_free(revwalk);

  return result;
}

int main() {
  git_libgit2_init();

  git_repository* repo;
  assert(git_repository_open_ext(&repo, getenv("PWD"), 0, NULL) == GIT_OK);

  for (unsigned i = 0; i < 50; i++) {
    const char *ref1 = "refs/heads/master";
    const char *ref2 = "refs/remotes/origin/master";

    unsigned ahead_count = count_commits_between_refs(repo, ref1, ref2);
    unsigned behind_count = count_commits_between_refs(repo, ref2, ref1);
    printf("%u ahead, %u behind\n", ahead_count, behind_count);
  }

  return 0;
}
```

3. Compile this program against the branch of libgit2. Side note: when trying to build libgit2 on macOS, I had trouble linking against openssl. So I build the static libraries using our node.js wrapper module: [git-utils](https://github.com/atom/git-utils) and compiled against them like this:

```sh
clang                  \
  -I libgit2/include   \
  zlib.a               \
  http_parser.a        \
  git2.a               \
  test.c
```

4. Run this program

### Expected behavior

The program should exit immediately, outputting "0 ahead, 0 behind" repeated 50 times.

### Actual behavior

The program takes 4 seconds to run.

### Version of libgit2 (release number or SHA1)

The head of master as of today: 42f8384045ca325c6885be21a89c3d8027995e03. I was also able to reproduce this against libgit2 0.26.0.

The problem does *not* happen with libgit2 0.24.0.

### Operating system(s) tested

Mac OS 10.13.16

/cc @carlosmn

### PR DESCRIPTION
**Pull request by carlosmn**
When porting, we overlooked that the difference between git's and our's time
representation and copied their way of getting the max value.
    
Unfortunately git was using unsigned integers, so `~0ll` does correspond to
their max value, whereas for us it corresponds to `-1`. This means that we
always consider the last date to be smaller than the current commit's and always
think commits are interesting.
    
Change the initial value to the macro that gives us the maximum value on each
platform so we can accurately consider commits interesting or not.

The second commit is mostly just to reduce the drift from git, the actual perf difference should be negligible.

This fixes #4740 and we should backport it as it fixes a regression.

### CODE REVIEW

**Comment by neithernut** [comment]
I've just ran and timed the reproducers from #4428 and a trimmed version of the reproducer in #4740 (single iteration) on the linux kernel repo.

----

The times reported for libgit2 built from master (bc34cb63ff5b2bc51bcdec7dfc41202dfc34e97f):

#4428:

    real	0m18.426s
    user	0m18.187s
    sys	0m0.227s

#4740:

    real	0m36.638s
    user	0m36.372s
    sys	0m0.236s

----

For the current tip (12a1790d8e71087056d2b2de936ddae439e1d94c)

#4428:

    real	0m18.413s
    user	0m18.156s
    sys	0m0.246s

#4740:

    real	0m0.007s
    user	0m0.005s
    sys	0m0.002s

----

Honestly, I thought I did something wrong when I performed the second measurement for the #4428 reproducer, but apparently this particular regression is not resolved. However, the performance is much better for #4740.

**Comment by carlosmn** [comment]
#4428 doesn't actually seem like a regression, but a fix and a misunderstanding of what different flags ought to do.

**Comment by ethomson** [comment]
Ouch!  Thanks for the fix, @carlosmn.

File: src/revwalk.c [hunk 1]
```diff
@@ -405,7 +405,7 @@ static int still_interesting(git_commit_list *list, int64_t time, int slop)
 static int limit_list(git_commit_list **out, git_revwalk *walk, git_commit_list *commits)
 {
 	int error, slop = SLOP;
-	int64_t time = ~0ll;
+	int64_t time = INT64_MAX;
```
Comment (pks-t) [inline src/revwalk.c]: I'm surprised none of our tests catched this :(

Comment (carlosmn) [reply src/revwalk.c]: It's just a performance regression, as all this does is make us think that we never went back far enough. If we had perf tests, maybe we would have caugh tit.

**Comment by pks-t** [comment]
On Sat, Sep 22, 2018 at 12:32:52PM -0700, Carlos Martín Nieto wrote:
> carlosmn commented on this pull request.
> > @@ -405,7 +405,7 @@ static int still_interesting(git_commit_list *list, int64_t time, int slop)
>  static int limit_list(git_commit_list **out, git_revwalk *walk, git_commit_list *commits)
>  {
>  	int error, slop = SLOP;
> -	int64_t time = ~0ll;
> +	int64_t time = INT64_MAX;
> 
> It's just a performance regression, as all this does is make us think that we never went back far enough. If we had perf tests, maybe we would have caugh tit.

Yeah, I realized that at a later point, too. But thanks for
clarifying!
