### PR TITLE
Prevent reading out of bounds memory

### LINKED ISSUE #4993: git_apply corrupts file if no NL at EOF
### Reproduction steps

- Create a file `lipsum.txt` with the following contents (no NL at EOF!)

```
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Nam lacinia hendrerit nibh, at tempor erat cursus eu.
In eros2 urna, aliquet id sodales vel, rhoncus nec ipsum.
Praesent dapibus risus eu metus egestas vehicula.
Morbi in condimantum risus, auctor malesuada massa.
Sed auctor, tellus at finibus convallis, massa lectus iaculis urna, eget malesuada ligula nunc at lacus.
Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
Vivamus vitae tortor erat.
Duis vitae pharetra sapien.
Integer auctor lacus sapien, vel vehicula ex mollis eu.
Cras odio ligula, ultrices ac facilisis in, volutpat eget metus.
In sed tincidunt felis, ut fringilla nisl.
Ut suscipit quam in lacus posuere semper.
Ut luctus vitae mi non faucibus.
Integer sit amet tortor nec lectus dapibus interdum vitae et nibh.
Morbi eget urna id dolor gravida posuere sit amet non diam.
Suspendisse sit amet diam dui.
```

- Commit the file
- Apply the following patch (from buffer)

```
diff --git a/lipsum.txt b/lipsum.txt
index b071d73..b70d77a 100644
--- a/lipsum.txt
+++ b/lipsum.txt
@@ -1,6 +1,6 @@
 Lorem ipsum dolor sit amet, consectetur adipiscing elit.
 Nam lacinia hendrerit nibh, at tempor erat cursus eu.
+In eros urna, aliquet id sodales vel, rhoncus nec ipsum.
-In eros2 urna, aliquet id sodales vel, rhoncus nec ipsum.
 Praesent dapibus risus eu metus egestas vehicula.
 Morbi in condimantum risus, auctor malesuada massa.
 Sed auctor, tellus at finibus convallis, massa lectus iaculis urna, eget malesuada ligula nunc at lacus.
```
### Expected behavior

The patch applies cleanly

### Actual behavior

The patch applies, but produces garbage characters at the end of the resulting file `<0x00>somerandommenorycontents`

### Version of libgit2 (release number or SHA1)

`master@1a107fac0fc88a4d74b64ffc9ae2fd178ba631c0` `v0.28.0-rc1`

### Operating system(s) tested

macOS 10.14.3 (18D109)

### PR DESCRIPTION
**Pull request by eaigner**
Closes #4993

### CODE REVIEW

**Comment by eaigner** [comment]
Test suite runs through, not quite sure how to distill a test case from this though.

File: AUTHORS [hunk 1]
```diff
@@ -23,6 +23,7 @@ Dmitry Kovega
 Emeric Fermas
 Emmanuel Rodriguez
 Eric Myhre
+Erik Aigner
```
Comment (pks-t) [inline AUTHORS]: Oh, been a long time since this file actually got amended. I'm still not part of it myself :P

File: src/apply.c [hunk 2]
```diff
@@ -59,7 +59,7 @@ static int patch_image_init_fromstr(
 	git_pool_init(&out->pool, sizeof(git_diff_line));
 
 	for (start = in; start < in + in_len; start = end) {
-		end = memchr(start, '\n', in_len);
+		end = memchr(start, '\n', in_len - (start - in));
```
Comment (pks-t) [inline src/apply.c]: I usually try to not be over-eager in enforcing commit message style, but in this case I think it'd help quite a lot if your commit actually explains the overflow and says why this change is necessary. It'd also make reviewing a lot easier for us :)

While already at it, you might also adjust the subject line of the commit message to something like e.g. "apply: prevent OOB read when reading patch image", just so that we know on first sight that the fix is about our apply code.

Comment (pks-t) [reply src/apply.c]: By the way: it's not necessary to have the ticket ID in commit messages. After all, if we ever decide to move to a ticketing system other than GitHub, then those might get invalidated either way.

**Comment by pks-t** [comment]
I've added a test that catches the OOB read and changed the commit message. Naturally, I've kept the authorship of your commit, so I hope you don't mind :)

**Comment by eaigner** [comment]
Thanks for the edits. The other issue was #4972, but I'm not sure if it is related.

**Comment by pks-t** [comment]
Oh, that was it, thanks for reminding me. This definitely isn't related at all

**Comment by pks-t** [comment]
Thanks a lot, @eaigner! :)
