### PR TITLE
Clear data after negotiation

### LINKED ISSUE #6889: depth option does not seem to work with libssh2
Setting the `depth` parameter doesn't seem to work when using the libssh2 backend.

### Reproduction steps

Modify the clone example to set the depth parameter:

```diff
diff --git a/examples/clone.c b/examples/clone.c
index 22d9d9b61..d8873cef1 100644
--- a/examples/clone.c
+++ b/examples/clone.c
@@ -90,6 +90,7 @@ int lg2_clone(git_repository *repo, int argc, char **argv)
 	clone_opts.fetch_opts.callbacks.transfer_progress = &fetch_progress;
 	clone_opts.fetch_opts.callbacks.credentials = cred_acquire_cb;
 	clone_opts.fetch_opts.callbacks.payload = &pd;
+	clone_opts.fetch_opts.depth = 1;

 	/* Do the clone */
 	error = git_clone(&cloned_repo, url, path, &clone_opts);
```

Build with libssh2:

`cmake -DUSE_SSH=libssh2 -DBUILD_EXAMPLES=on ..`

Run the example trying to clone an ssh URL:

```
./examples/lg2 clone ssh://git@github.com/libgit2/libgit2.git asdf
SSH Key: /Users/eric/.ssh/id_ed25519
Password: ...

ERROR 12: could not read from remote repository
Bad news:
 could not read from remote repository
```

Note that it works with the `exec` backend.

### Expected behavior

Should be able to set depth with SSH.

### Actual behavior

Get GIT_EEOF GIT_ERROR_NET error.

### Version of libgit2 (release number or SHA1)

9f3406163bf85eec75c6095154a27d3be7448b45

### Operating system(s) tested

macOS

### PR DESCRIPTION
**Pull request by lrm29**
Fixes #6889.

I'm not sure why this works with https and not ssh. There are claims it works with the ssh "exec" backend but that wasn't the case for me.

Because we don't clear the data buffer, the "wants" get sent twice to the server. The second time is the call to  git_smart__negotiation_step in line 568 of smart_protocol.c

### CODE REVIEW

**Comment by lrm29** [comment]
Just as well we have tests for this... I think I'm on the right lines here though.

File: src/libgit2/transports/smart_protocol.c [hunk 1]
```diff
@@ -433,6 +433,7 @@ int git_smart__negotiate_fetch(
 
 		if ((error = git_smart__negotiation_step(&t->parent, data.ptr, data.size)) < 0)
 			goto on_error;
+		git_str_clear(&data);
```
Comment (ethomson) [inline src/libgit2/transports/smart_protocol.c:436]: You are indeed - I think that you need to differentiate the clearing of data based on whether we're in RPC mode (HTTP) or not (SSH).

```suggestion

		if (!t->rpc)
			git_str_clear(&data);
```

?
