### PR TITLE
submodule: Try to fetch when update fails to find the target commit.

### LINKED ISSUE #3783: git_submodule_update doesn't fetch
When a repository is fetched without recursively fetching its submodules git_submodule_update can fail with missing target commit in the submodule. I believe that core git has some logic to fetch if the submodule doesn't have the target object.

### PR DESCRIPTION
**Pull request by hackhaslam**
This fixes #3783. When submodule update doesn't find the target commit in the submodule, fetch from the default remote and then try to lookup the commit again.

### CODE REVIEW

**Comment by ethomson** [comment]
@jamill Would you have a moment to spare a second set of eyes here?  I realize that you're not spending as much time with submodules these days, but you certainly still know more about them than I do.  :)

File: src/submodule.c [hunk 1]
```diff
@@ -1171,9 +1172,21 @@ int git_submodule_update(git_submodule *sm, int init, git_submodule_update_optio
...
-			(error = git_object_lookup(&target_commit, sub_repo, git_submodule_index_id(sm), GIT_OBJ_COMMIT)) < 0 ||
-			(error = git_checkout_tree(sub_repo, target_commit, &update_options.checkout_opts)) != 0 ||
+		if ((error = git_submodule_open(&sub_repo, sm)) < 0)
+			goto done;
+
+		/**
+		 * Look up the target commit in the submodule.
+		 * If it isn't found then fetch and try again.
+		 */
+		if ((error = git_object_lookup(&target_commit, sub_repo, git_submodule_index_id(sm), GIT_OBJ_COMMIT)) < 0) {
```
Comment (jamill) [inline src/submodule.c]: Is there a specific error code that is returned when the target commit could not be found? Could we be more selective and only attempt to fetch for the `not found` error?

**Comment by jamill** [comment]
Looks OK to me - and I think this matches the expected behavior. I might also suggest updating the comments for this function to clarify that this will fetch if there are missing commits. Thanks!

**Comment by hackhaslam** [comment]
Thanks for the review! I restricted the fetch logic to the not found error, and changed the documenation comment to mention the new behavior. I also made a slight drive-by fix for a duplicate check in the clone side.

I'm noticing now that `submodule update` has a `-no-fetch` flag. Maybe there should be a `no_fetch` flag in the submodule update options? Probably not a big deal though.

**Comment by ethomson** [comment]
> I'm noticing now that submodule update has a -no-fetch flag. Maybe there should be a no_fetch flag in the submodule update options? Probably not a big deal though.

I agree, that would be a really nice option.  Is this something you want to tackle in this PR or do you want me to merge this and tackle this later?

**Comment by hackhaslam** [comment]
I guess that I should probably add it in this PR so that I don't forget it. I'll add it soon.

**Comment by hackhaslam** [comment]
I added the flag. I also made another small drive-by fix to the version used in the update options initializer.

**Comment by ethomson** [comment]
> I also made another small drive-by fix to the version used in the update options initializer.

Good catch on that one.  👌 Thanks!
