### PR TITLE
Fix stash save bug with fast path index check

### LINKED ISSUE #4101: Stash save does not behave the same as command line
### Reproduction steps
1. Create a stash using git_stash_save with default options.
2. use `git show stash@{0}` in command line
3. There are no diffs for the stash

### Expected behavior
The expected behavior is that the stashed diffs are visible in command line.

### Actual behavior
The diffs are not visible via command line.

### Version of libgit2 (release number or SHA1)
37dba1a739b5ee6c45dc9f3c0bd1f7f7a18f13f7
### Operating system(s) tested
Linux, Mac OSX

### PR DESCRIPTION
**Pull request by novalis**
If the index contains stat data for a modified file, and the file is
not racily dirty, and there exists an untracked working tree directory
alphabetically after that file, and there are no other changes to the
repo, then git_stash_save would fail. It would confuse the untracked
working tree directory for the modified file, because they have the
same sha: zero.  The wt directory has a sha of zero because it's a
directory, and the file would have a zero sha because we wouldn't read
the file -- we would just know that it doesn't match the index.  To
fix this confusion, we simply check mode as well as SHA.

Fixes #4101

### CODE REVIEW

**Comment by novalis** [comment]
Of course, this fix is just a point fix, and it's possible that there's a cleaner way to solve this. But it does work.

File: tests/stash/save.c [hunk 1]
```diff
@@ -188,6 +188,46 @@ void test_stash_save__can_include_untracked_and_ignored_files(void)
...
+	const char *paths[] = {"what", "where", "how", "why"};
+	git_reference *head;
+	git_commit *head_commit;
+
+	const char* workdir = git_repository_workdir(repo);
+	size_t len = strlen(workdir);
+	char* untracked_dir = malloc(len + 2);
+
+	strcpy(untracked_dir, workdir);
+	strcpy(untracked_dir + len, "z");
```
Comment (pks-t) [inline tests/stash/save.c]: I'd prefer to just use `git_buf` instead of pointer arithmetic. I mean this here is simple enough and unlikely to break, but `git_buf_printf(&untracked_dir, "%sz", workdir)`s is more readable.

File: tests/stash/save.c [hunk 2]
```diff
@@ -188,6 +188,46 @@ void test_stash_save__can_include_untracked_and_ignored_files(void)
...
+void test_stash_save__untracked_regression(void)
+{
+	git_checkout_options opts = GIT_CHECKOUT_OPTIONS_INIT;
+	const char *paths[] = {"what", "where", "how", "why"};
+	git_reference *head;
+	git_commit *head_commit;
+
+	const char* workdir = git_repository_workdir(repo);
+	size_t len = strlen(workdir);
+	char* untracked_dir = malloc(len + 2);
```
Comment (pks-t) [inline tests/stash/save.c]: Pointers belong with the variable :)

File: src/diff_generate.c [hunk 3]
```diff
@@ -273,7 +273,8 @@ static git_diff_delta *diff_delta__last_for_item(
 		break;
 	case GIT_DELTA_MODIFIED:
 		if (git_oid__cmp(&delta->old_file.id, &item->id) == 0 ||
-			git_oid__cmp(&delta->new_file.id, &item->id) == 0)
+		    (delta->new_file.mode == item->mode &&
```
Comment (pks-t) [inline src/diff_generate.c]: Do modes have to be completely the same? I get that it doesn't make sense in case one is a directory and the other is not. But what about when e.g. 644 changes to 755?

Comment (novalis) [reply src/diff_generate.c]: I have to admit that I don't really understand this code.  It seems completely weird to me that something gets added to the diff list and then later removed.  But gdb shows the "mode" for a directory as 16384 -- that is, these are git modes, not filesystem modes.  And looking at all three of the callers, they only happen in the case where one side of the comparison is a directory. So I don't think mode changes are relevant here.  What do you think?

Comment (ethomson) [reply src/diff_generate.c]: Goodness, I don't know what this code is doing, either.

Comment (novalis) [reply src/diff_generate.c]: If the question is "should X get removed from the list of diffs because it's actually identical to this other thing", I think a mode change should give the answer "no", because there is still a diff. 

(But, again, there's no case where this is called on two files; one arg is always a directory)

**Comment by ethomson** [comment]
Ok, I stepped through here a few times to convince myself that I understood what was going on again.  Thanks for digging into this; our diff code is not trivial!  :D
