### PR TITLE
Ensure that `git_index_add_all` handles ignored directories

### LINKED ISSUE #6517: .gitignore breaks git_index_add_all in certain cases
### Reproduction steps

Add `.gitignore` containing the following specification

```
.idea
```

Create a directory with ignore name.
Create a file inside it.

Construct a `git_repository` from the repo and invoke 
```
git_index_add_all(
        index,
        /* pathspec = */ nullptr,
        GIT_INDEX_ADD_FORCE,
        /* callback = */ nullptr,
        /* payload = */ nullptr
)
```
### Actual behavior

Receive a git_error with `code=-1`, `message=invalid path: '.idea/`.
 
### Expected behavior

Necessary files are added to the index just like original git does.
Why .gitignore affects this routine despite the explicit request to be ignored?

### Version of libgit2 (release number or SHA1)

1.5.0

### Operating system(s) tested

linux-x86_64

### PR DESCRIPTION
**Pull request by ethomson**
When all files beneath a directory are ignored, our diff machinery will return the directory itself. Obviously we do not operate on directories in the index, so `git_index_add_all` should ignore this case.

Fixes #6517

### CODE REVIEW

File: src/libgit2/index.c [hunk 1]
```diff
@@ -3453,6 +3453,13 @@ static int apply_each_file(const git_diff_delta *delta, float progress, void *pa
 		    &match, NULL))
 		return 0;
 
+	/*
+	 * diff returns the directory when all files are ignored; we never
```
Comment (georgthegreat) [inline src/libgit2/index.c:3457]: Is this behavior of diff intentional?
Filtering out trees in function named apply_each_file looks ... weird.

**Comment by georgthegreat** [comment]
Unfortunately this does not work as intended.
GIT_INDEX_ADD_FORCE should add ignored files disregarding .gitignore contents.

At the time `/folder/asdf` is not added to the index (this is what I am seeing in my local executions with this patch applied).

**Comment by ethomson** [comment]
> GIT_INDEX_ADD_FORCE should add ignored files disregarding .gitignore contents.

Ah, yes, thanks. I had it flipped around in my head.

In any case, the problem here is that diff coalesces a folder that has contents that are all ignored into a single diff entry. We need to expand that out to add files to the index. This update should do that.

**Comment by georgthegreat** [comment]
@ethomson the latest version works for us.
Thanks a lot for the quick fix!
