### PR TITLE
Longpath filter bug

### LINKED ISSUE #6054: git_index_add_bypath fails with "path too long" when longpaths is true and filters are set
### Reproduction steps

Add a test similar to test_win32_longpath__status_and_add but set "core.autocrlf" to true:

```
void test_win32_longpath__status_and_add_with_filter(void)
{
#ifdef GIT_WIN32
	git_repository *repo = cl_git_sandbox_init("testrepo");
	git_index *index;
	git_buf out = GIT_BUF_INIT;
	unsigned int status_flags;

	cl_repo_set_bool(repo, "core.longpaths", true);
        cl_repo_set_bool(repo, "core.autocrlf", true);
	cl_git_pass(git_repository_workdir_path(&out, repo, LONG_FILENAME));

	cl_git_rewritefile(out.ptr, "This is a long path.\r\n");

	cl_git_pass(git_status_file(&status_flags, repo, LONG_FILENAME));
	cl_assert_equal_i(GIT_STATUS_WT_NEW, status_flags);

	cl_git_pass(git_repository_index(&index, repo));
	cl_git_pass(git_index_add_bypath(index, LONG_FILENAME));

	cl_git_pass(git_status_file(&status_flags, repo, LONG_FILENAME));
	cl_assert_equal_i(GIT_STATUS_INDEX_NEW, status_flags);

	git_index_free(index);
	git_buf_dispose(&out);
#endif
}
```

### Expected behavior

git_index_add_bypath passes.

### Actual behavior

git_index_add_bypath fails. The reason is this function is called with a null git_repository:

bool should_validate_longpaths(git_repository *repo);

The function git_blob__create_from_paths calls write_file_filtered but doesn't pass the git_repository down to git_filter_list_apply_to_file.

A simple fix would be to pass the git_repository to write_file_filtered. I'll create a pull request with this idea.

### Version of libgit2 (release number or SHA1)

v1.2.0.

### Operating system(s) tested

Windows.

### PR DESCRIPTION
**Pull request by lrm29**
Fixes #6054.

An alternative might be to handle the null git_repository case in the longpath check ((bool) should_validate_longpaths(git_repository *repo)). Could also put an assert on "repo" argument in should_validate_longpaths.

### CODE REVIEW

File: tests/win32/longpath.c [hunk 1]
```diff
@@ -64,15 +64,11 @@ void test_win32_longpath__workdir_path_validated(void)
 #endif
 }
 
-void test_win32_longpath__status_and_add(void)
-{
-#ifdef GIT_WIN32
-	git_repository *repo = cl_git_sandbox_init("testrepo");
+static void assert_longpath_status_and_add(git_repository* repo) {
 	git_index *index;
```
Comment (ethomson) [inline tests/win32/longpath.c:68]:
```suggestion
#ifdef GIT_WIN32
static void assert_longpath_status_and_add(git_repository* repo) {
	git_index *index;
```

File: tests/win32/longpath.c [hunk 2]
```diff
@@ -88,5 +84,27 @@ void test_win32_longpath__status_and_add(void)
 
 	git_index_free(index);
 	git_buf_dispose(&out);
+}
```
Comment (ethomson) [inline tests/win32/longpath.c:87]:
```suggestion
}
#endif
```

**Review by ethomson — CHANGES_REQUESTED** [review]

**Comment by ethomson** [comment]
Looks good to me - we'll need to `ifdef` around that new function to prevent unused warnings, but otherwise 👍

**Comment by ethomson** [comment]
Thanks for the fix.  I changed the unit test a bit in 005c740b15bf2b77e5ef1112aed887751fc2c827 to check the contents in the repo to ensure that filtering was applied.
