### PR TITLE
 object: git_object_short_id fails with core.abbrev string values

### LINKED ISSUE #6878: git_object_short_id fails with core.abbrev string values
### Reproduction steps

1. Set up a global config setting `core.abbrev` to a string value: `git config --global core.abbrev no`
2. Run a program that uses `git_object_short_id`.

```c
#include <assert.h>
#include <git2/repository.h>
#include <git2/errors.h>
#include <git2/revparse.h>
#include <git2/oid.h>
#include <git2/global.h>
#include <stdio.h>
#include <unistd.h>

int main() {
  git_repository *repo;
  assert(git_libgit2_init() == 1);
  assert(git_repository_open(&repo, "..") == 0);

  git_object *obj;
  assert(git_revparse_single(&obj, repo, "HEAD") == 0);
  git_buf buf = {0};
  int rc;
  rc = git_object_short_id(&buf, obj);
  if (rc == 0) {
    fprintf(stderr, "short: %s", buf.ptr);
  } else {
    git_error const *err;
    err = git_error_last();
    fprintf(stderr, "error: class=%i: %s", err->klass, err->message);
  }

  return 0;
}
```

Note that the config value can take the values:
* false, no, off — added in git 2.11.1 (ref https://github.com/git/git/commit/48d5014dd42cc4a4465162c9807eaa253715e105)
* auto — added in git 2.31 (ref https://github.com/git/git/commit/a9ecaa06a7235e62a9cf4703a19463fcee4449c7)

### Expected behavior

Should be able to handle string values.

### Actual behavior

Fails with:

`error: class=7: failed to map 'no'`

### Version of libgit2 (release number or SHA1)

403a03b3beaea7d26b9515e27dd36553239647ca

### Operating system(s) tested

any

### PR DESCRIPTION
**Pull request by lrm29**
Fixes #6878.

Not sure if I went to far here, I noticed core.abbrev was used by diff_print.c. If the user sets core.abbrev to an integer outside of the allowed range that will now error.

I also added GIT_ABBREV_MINIMUM, which Git sets to 4. libgit2 was allowing anything above zero.

### CODE REVIEW

File: src/libgit2/object.c [hunk 1]
```diff
@@ -536,12 +561,13 @@ static int git_object__short_id(git_str *out, const git_object *obj)
...
 
-	if ((error = git_repository__configmap_lookup(&len, repo, GIT_CONFIGMAP_ABBREV)) < 0)
+	if ((error = git_object__abbrev_length(&len, repo)) < 0)
 		return error;
 
-	if (len < 0 || (size_t)len > oid_hexsize) {
-		git_error_set(GIT_ERROR_CONFIG, "invalid oid abbreviation setting: '%d'", len);
-		return -1;
+	if ((size_t)len == oid_hexsize) {
+		if ((error = git_oid_cpy(&id, &obj->cached.oid)) < 0) {
```
Comment (lrm29) [inline src/libgit2/object.c:568]: Should we early return here?

File: src/libgit2/object.c [hunk 2]
```diff
@@ -520,13 +520,38 @@ int git_object_lookup_bypath(
 	return error;
 }
 
+int git_object__abbrev_length(int *out, git_repository *repo)
```
Comment (ethomson) [inline src/libgit2/object.c:523]: I think that probably this should be in the `git_repository` group, instead of `git_object`. (It's really about the repository's abbreviation settings.) This is a minor nit, and I've kept you waiting on a review for a long time, so I'm happy to make this change later today if you prefer. 🙏 

Thanks for investigating and fixing.

Comment (lrm29) [reply src/libgit2/object.c:523]: Will move to git_repository__abbrev_length. I just happened to run into this issue and used it to get more practice with C, no rush :)

File: tests/libgit2/object/shortid.c [hunk 3]
```diff
@@ -49,3 +48,43 @@ void test_object_shortid__select(void)
...
+	cl_assert_equal_s("ce013625030ba8dba906f756967f9e9ca394464a", shorty.ptr);
+
+	cl_git_pass(git_config_set_string(cfg, "core.abbrev", "4"));
+	cl_git_pass(git_object_short_id(&shorty, obj));
+	cl_assert_equal_i(4, shorty.size);
+	cl_assert_equal_s("ce01", shorty.ptr);
+
+	cl_git_pass(git_config_set_string(cfg, "core.abbrev", "3"));
+	cl_git_fail(git_object_short_id(&shorty, obj));
+	cl_git_pass(git_config_set_string(cfg, "core.abbrev", "41"));
```
Comment (ethomson) [inline tests/libgit2/object/shortid.c:80]: In fact, git handles very large `core.abbrev` settings by converting them to the max length.

```
git -c core.abbrev=4242 log
commit 1738f891a1eca8d94ba1cffcabd1ec41af122c52 (HEAD -> main, origin/main, origin/HEAD)
Merge: 27d82f15cdf572399fe0c58853e497642096957a 7668c13552cc1090608726bb871f57ac4f7eab83
...
```

**Comment by ethomson** [comment]
Wow, there's some fun things going on here in git compatibility land:

1. `core.abbrev=0` (an integer value) fails, but `core.abbrev=false` (a boolean value) succeeds.
2. `core.abbrev=999` succeeds (clamping to the max oid length)

:sigh:

File: src/libgit2/config_cache.c [hunk 4]
```diff
@@ -64,11 +64,10 @@ static git_configmap _configmap_logallrefupdates[] = {
...
 };
 
-/*
- * Generic map for integer values
- */
-static git_configmap _configmap_int[] = {
+static git_configmap _configmap_abbrev[] = {
+	{GIT_CONFIGMAP_FALSE, NULL, GIT_ABBREV_FALSE},
 	{GIT_CONFIGMAP_INT32, NULL, 0},
+	{GIT_CONFIGMAP_STRING, "auto", GIT_ABBREV_DEFAULT}
```
Comment (ethomson) [inline src/libgit2/config_cache.c:70]: I think that you need to invert the bool and int cases so that `0` can be correctly identified as an invalid input, but `false` is allowed. Otherwise, we treat the `0` as falsey.

```suggestion
static git_configmap _configmap_abbrev[] = {
	{GIT_CONFIGMAP_INT32, NULL, 0},
	{GIT_CONFIGMAP_FALSE, NULL, GIT_ABBREV_FALSE},
	{GIT_CONFIGMAP_STRING, "auto", GIT_ABBREV_DEFAULT}
```

File: src/libgit2/repository.c [hunk 5]
```diff
@@ -4009,3 +4009,28 @@ int git_repository_commit_parents(git_commitarray *out, git_repository *repo)
...
+		return error;
+
+	if (len == GIT_ABBREV_FALSE) {
+		len = (int)oid_hexsize;
+	}
+
+	if (len < GIT_ABBREV_MINIMUM || (size_t)len > oid_hexsize) {
+		git_error_set(GIT_ERROR_CONFIG, "invalid oid abbreviation setting: '%d'", len);
+		return -1;
+	}
```
Comment (ethomson) [inline src/libgit2/repository.c:4031]: I think that we should invert these tests so that we can handle large values.

```suggestion
	if (len < GIT_ABBREV_MINIMUM) {
		git_error_set(GIT_ERROR_CONFIG, "invalid oid abbreviation setting: '%d'", len);
		return -1;
	}

	if (len == GIT_ABBREV_FALSE || (size_t)len > oid_hexsize)
		len = (int)oid_hexsize;
```

File: src/libgit2/repository.h [hunk 6]
```diff
@@ -102,6 +102,8 @@ typedef enum {
 	/* core.trustctime */
 	GIT_TRUSTCTIME_DEFAULT = GIT_CONFIGMAP_TRUE,
 	/* core.abbrev */
+	GIT_ABBREV_FALSE = GIT_CONFIGMAP_FALSE,
```
Comment (ethomson) [inline src/libgit2/repository.h:105]:
```suggestion
	GIT_ABBREV_FALSE = INT_MAX,
```

This could be `GIT_OID_MAX_HEXSIZE` which might be more obvious to the reader?

File: tests/libgit2/object/shortid.c [hunk 7]
```diff
@@ -49,3 +48,43 @@ void test_object_shortid__select(void)
...
+	cl_git_fail(git_object_short_id(&shorty, obj));
```
Comment (ethomson) [inline tests/libgit2/object/shortid.c:81]:
```suggestion
	cl_git_pass(git_config_set_string(cfg, "core.abbrev", "0"));
	cl_git_fail(git_object_short_id(&shorty, obj));
	cl_git_pass(git_config_set_string(cfg, "core.abbrev", "3"));
	cl_git_fail(git_object_short_id(&shorty, obj));
```

File: tests/libgit2/object/shortid.c [hunk 8]
```diff
@@ -49,3 +48,43 @@ void test_object_shortid__select(void)
...
+	cl_git_pass(git_config_set_string(cfg, "core.abbrev", "auto"));
+	cl_git_pass(git_object_short_id(&shorty, obj));
+	cl_assert_equal_i(7, shorty.size);
+	cl_assert_equal_s("ce01362", shorty.ptr);
+
+	cl_git_pass(git_config_set_string(cfg, "core.abbrev", "off"));
+	cl_git_pass(git_object_short_id(&shorty, obj));
+	cl_assert_equal_i(40, shorty.size);
+	cl_assert_equal_s("ce013625030ba8dba906f756967f9e9ca394464a", shorty.ptr);
+
```
Comment (ethomson) [inline tests/libgit2/object/shortid.c:72]:
```suggestion

	cl_git_pass(git_config_set_string(cfg, "core.abbrev", "false"));
	cl_git_pass(git_object_short_id(&shorty, obj));
	cl_assert_equal_i(40, shorty.size);
	cl_assert_equal_s("ce013625030ba8dba906f756967f9e9ca394464a", shorty.ptr);

	cl_git_pass(git_config_set_string(cfg, "core.abbrev", "99"));
	cl_git_pass(git_object_short_id(&shorty, obj));
	cl_assert_equal_i(40, shorty.size);
	cl_assert_equal_s("ce013625030ba8dba906f756967f9e9ca394464a", shorty.ptr);

```

**Review by ethomson — COMMENTED** [review]
Some notes after poking with this in the context of git itself.

**Comment by lrm29** [comment]
> Wow, there's some fun things going on here in git compatibility land:
> 
>     1. `core.abbrev=0` (an integer value) fails, but `core.abbrev=false` (a boolean value) succeeds.
> 
>     2. `core.abbrev=999` succeeds (clamping to the max oid length)
> 
> 
> :sigh:

Good spots.

1) I missed that, git has a [git_parse_maybe_bool_text]( https://github.com/git/git/blob/caacdb5dfd60540ecec30ec479f147f3c8167e11/config.c#L1458) which doesn't allow 0.

2) Erroring was the existing libgit2 behaviour right? But Git compatibility wins...

**Comment by ethomson** [comment]
> But Git compatibility wins...

We aim to be bug-for-bug compatible. 🤣 😭

**Comment by ethomson** [comment]
Thanks for the fix!

**Review by ethomson — APPROVED** [review]
