### PR TITLE
clone example: don't divide by zero

### LINKED ISSUE #2812: clone bare repo ended with"Floating point exception"
The bug had been founded while testing the exampel code, and still seen in the latest v0.22.0-rc1-11-g1646412 release.  Run command:
./git2 clone path_to_bare_repo path

### PR DESCRIPTION
**Pull request by ethomson**
Local transports don't have data about the size, avoid dividing by
zero in the callback.

Fixes #2812

### CODE REVIEW

File: examples/network/clone.c [hunk 1]
```diff
@@ -18,8 +18,14 @@ typedef struct progress_data {
 
 static void print_progress(const progress_data *pd)
 {
-	int network_percent = (100*pd->fetch_progress.received_objects) / pd->fetch_progress.total_objects;
-	int index_percent = (100*pd->fetch_progress.indexed_objects) / pd->fetch_progress.total_objects;
+	int network_percent, index_percent;
+
+	if (!pd->fetch_progress.total_objects || !pd->total_steps)
```
Comment (Therzok) [inline examples/network/clone.c]: Isn't `total_steps` checked below?

**Comment by Therzok** [comment]
That looks way better. :+1:

**Comment by ethomson** [comment]
Thanks, @Therzok !
