### PR TITLE
revparse: support open-ended ranges

### LINKED ISSUE #4223: One-sided revision ranges not supported
Command-line git supports leaving one side of a revision range blank, like `origin/master...`. When unspecified, the revision defaults to HEAD. Currently, libgit2 doesn't support these revision formats.

### Reproduction steps

Run `examples/rev-parse` with one-sided revision ranges.

### Expected behavior

The same as command-line git:

```
$ git rev-parse ..HEAD~1
d476d024d0415a566b858daec7faa961587bae14
^f9d3b0d05f19a59e3327deabc2edc93e507c6aa3

$ git rev-parse HEAD~1..
f9d3b0d05f19a59e3327deabc2edc93e507c6aa3
^d476d024d0415a566b858daec7faa961587bae14
```

### Actual behavior

```
$ examples/rev-parse ..HEAD~1
Could not parse '..HEAD~1' [-12] - failed to parse revision specifier - Invalid pattern ''

$ examples/rev-parse HEAD~1..
Could not parse 'HEAD~1..' [-12] - failed to parse revision specifier - Invalid pattern ''
```

### Version of libgit2 (release number or SHA1)
v0.16.0-8230-g89141d9

### Operating system(s) tested
MacOS 10.12.4

### PR DESCRIPTION
**Pull request by wabain**
Support '..' and '...' ranges where one or both sides are not
specified. The unspecified side defaults to HEAD.

Closes #4223

### CODE REVIEW

**Comment by ethomson** [comment]
Look at those beautiful tests!  😍 

Thanks for jumping in to fix this.  This is great, and I appreciate the pull request!

File: src/revparse.c [hunk 1]
```diff
@@ -899,9 +899,17 @@ int git_revparse(
...
+			&revspec->from,
+			repo,
+			*lstr == '\0' ? "HEAD" : lstr);
+
+		if (!error) {
+			error = git_revparse_single(
+				&revspec->to,
+				repo,
+				*rstr == '\0' ? "HEAD" : rstr);
+		}
```
Comment (pks-t) [inline src/revparse.c]: Note that this also supports the ranges ".." and "...", that is no limiter at all. While these seem nonsensical, it even seems to be the right thing as git.git also accepts these ranges:

```
$ git rev-parse ..
..
$ git rev-parse ...
a8c90ef62281db933118aa84489eb0e1e9cc347c
a8c90ef62281db933118aa84489eb0e1e9cc347c
^a8c90ef62281db933118aa84489eb0e1e9cc347c
```

While the first result stumps me, there at least is no error here.

Could you maybe add another two tests for these special-cases?

File: tests/refs/revparse.c [hunk 2]
```diff
@@ -749,6 +749,26 @@ void test_refs_revparse__parses_range_operator(void)
...
+
+	test_id("..HEAD~3",
+		"a65fedf39aefe402d3bb6e24df4d4f5fe4547750",
+		"4a202b346bb0fb0db7eff3cffeb3c70babbd2045",
+		GIT_REVPARSE_RANGE);
+
+	test_id("...HEAD~3",
+		"a65fedf39aefe402d3bb6e24df4d4f5fe4547750",
+		"4a202b346bb0fb0db7eff3cffeb3c70babbd2045",
+		GIT_REVPARSE_RANGE | GIT_REVPARSE_MERGE_BASE);
```
Comment (pks-t) [inline tests/refs/revparse.c]: Could you add two additional tests here to test the two special-cases of ".." and "...", please?

File: src/revparse.c (hunk 1 above)
Comment (wabain) [inline src/revparse.c]: I hadn't thought about it much because `man gitrevisions` seems to explicitly say that the empty ranges are allowed. ("Note that .. would mean HEAD..HEAD which is an empty range that is both reachable and unreachable from HEAD.") However, on inspection, git.git treats `..` as a special case [on purpose](https://github.com/git/git/commit/003c84f6d2b9e9c4d5bbf5262cae994bac7190cb) so that it's always handled as a path for potentially ambiguous commands like `git log ..`. If the argument is disambiguated, `git rev-parse` gives an error:

```
$ git rev-parse .. --
fatal: bad revision '..'
```

I think it makes sense to reject `..`, since trying to parse an argument as a revision and then as a path is a pretty common git CLI idiom. Continuing to allow `...` seems a bit weird, but it should probably be accepted since git.git supports it.

Comment (pks-t) [inline src/revparse.c]: Oh, that's what's going on here. The paragraph you probably mean from gitrevisions(7):

```
       In these two shorthand notations, you can omit one end and let it default to HEAD.
       For example, origin.. is a shorthand for origin..HEAD and asks "What did I do
       since I forked from the origin branch?" Similarly, ..origin is a shorthand for
       HEAD..origin and asks "What did the origin do since I forked from them?" Note that
       .. would mean HEAD..HEAD which is an empty range that is both reachable and
       unreachable from HEAD.
```

So it explicitly says that one can omit one end, only. So I think your reasoning about us rejecting when both sides are empty is correct.

**Comment by wabain** [comment]
I've updated to match git.git's behavior for the special cases '..' and '...'.

**Comment by ariksugeng** [comment]
Can ask for setting theme and product on my web

Pada tanggal Jum, Mei 5, 2017, 23:14 William Bain <notifications@github.com>
menulis:
