### PR TITLE
parse: Do not initialize the content in context to NULL

### LINKED ISSUE #4726: git__linenlen calls memchar with null pointer
### Reproduction steps
`git__linenlen` in `util.c` calls memchar with null pointer passed as argument 1.  Can be reproduced with the following code:

```
#include <git2.h>

int main()
{
    git_repository *repo = NULL;

    git_libgit2_init();
    git_repository_init(&repo, "testrepo", 0);
    git_repository_free(repo);

    return 0;
}
```

### Expected behavior

Avoid call to memchr with null pointer.

### Actual behavior

When I test memory access errors in the R bindings [git2r](https://github.com/ropensci/git2r) using Undefined Behavior Sanitizer, I see `libgit2/src/util.c:354:8: runtime error: null pointer passed as argument 1, which is declared to never be null`

### Version of libgit2 (release number or SHA1)

99bb98c0e8abb97b1daa3aff0307b93ed9291c08

### Operating system(s) tested

Fedora 28

### PR DESCRIPTION
**Pull request by neithernut**
String operations in libgit2 are supposed to never receive `NULL`, e.g. they are not `NULL`-save. In the case of `git__linenlen()`, invocation with `NULL` leads to undefined behavior.

In a `git_parse_ctx` however, the `content` field used in these operations was initialized to `NULL` if the `git_parse_ctx_init()` was called with `NULL` for `content` or `0` for `content_len`. For the latter case, the initialization function even contained some logic for initializing `content` with `NULL`.

This commit mitigates triggering undefined behavior by rewriting the logic. Now `content` is always initialized to a non-null buffer. Instead of a null buffer, an empty string is used for denoting an empty buffer.

Supersedes #4733. Resolves #4726.

### CODE REVIEW

File: src/parse.c [hunk 1]
```diff
@@ -8,12 +8,14 @@
...
-	if (content_len)
+	if (content && content_len) {
 		ctx->content = content;
-	else
-		ctx->content = NULL;
+		ctx->content_len = content_len;
+	} else {
+		ctx->content = "";
+		ctx->content_len = 0;
+	}
```
Comment (pks-t) [inline src/parse.c]: Yeah, this fixes the issue. I'm wondering though if we should even make it a bug to pass in `NULL` to `git_parse_ctx_init` by adding an assert. That'd require us to review all callers, though

Comment (neithernut) [reply src/parse.c]: That was my initial idea. In a (non-published) earlier version, I added an assertion for catching calls to `git_parse_ctx_init` with `NULL` for `context`. However, I quickly ran into places where this fails.

For example, functions for parsing stuff built upon `git_parse_ctx` would also happily pass `NULL` for `context`. I even run into a test case explicitly checking for the ability to parse a patch from an empty _and_ a `NULL` buffer:

https://github.com/libgit2/libgit2/blob/3be7301151e44537d2423386dc71f1d3e496c664/tests/apply/fromfile.c#L448

Comment (pks-t) [reply src/parse.c]: Huh, so be it then. Thanks for clarifying!
