### PR TITLE
Configuration parsing: validate section headers with quotes

### LINKED ISSUE #5072: Configuration parsing: Incorrect parsing of section header
### Reproduction steps

The parser skips any character between whitespace and `"` in between the section name and the subsection name.

Consider configuration file 
```
[x z "y"] a = 1
```

### Expected behavior

Error.

```
D:\repository>git config --list
fatal: bad config line 1 in file .git/config
```

### Actual behavior

libgit2 reads the configuration without reporting any error.

### Version of libgit2 (release number or SHA1)

a904fc6d12ffc20aa1a238a78000921494222e89

### Operating system(s) tested

Windows

### PR DESCRIPTION
**Pull request by ethomson**
When parsing configuration section headers, we previously stopped at the first space, and skipped to the first quotation mark.  This allows us to support valid section headers like `[foo "bar"]` or `[foo        "bar"]`.

However, by skipping from the end of the section name to the first quotation mark, we ignore any invalid characters there.  For example, `[foo skipped "bar"]` which is not legal.

Validate that there is only whitespace between the end of the section name and the first quotation mark.  This also adds additional tests that were useful for my understanding and should help prevent regression.

Fixes #5072

### CODE REVIEW

File: src/config_parse.c [hunk 1]
```diff
@@ -192,7 +191,7 @@ static int parse_section_header(git_config_parser *reader, char **section_out)
 	do {
 		if (git__isspace(c)){
 			name[name_length] = '\0';
-			result = parse_section_header_ext(reader, line, name, section_out);
+			result = parse_section_header_ext(reader, line, pos, name, section_out);
```
Comment (pks-t) [inline src/config_parse.c]: I really don't like this method name. It's not an extended version of the normal `parse_section_header`, but instead it parses the subsection-part of section headers (e.g. the quoted part). So I think it should just be called `parse_subsection_header` or something like that.

Comment (ethomson) [reply src/config_parse.c]: Agreed.  Fixed.
