### PR TITLE
commit: ignore multiple author fields

### LINKED ISSUE #3182: libgit2 fails to parse commit with dual author field from FreeSWITCH repo
```
git clone https://freeswitch.org/stash/scm/fs/freeswitch.git
```

Then open the repo with libgit2 and attempt to load the commit `487128950df6ee433c131b5feaafe81ee86629f4`. It will fail with the error "Failed to parse signature - expected prefix doesn't match actual".

If we look at the commit object with `git cat-file commit 487128950df6ee433c131b5feaafe81ee86629f4` we get:

    tree 070633dfc3ea352dfb1094822f477111e519a9ca
    parent cde20f6fe68523d9416d2fed72435a8ba880a269
    author Travis Cross <tc@traviscross.com> 1395382322 +0000
    author Anthony Minessale <anthm@freeswitch.org> 1394747953 +0500
    committer Travis Cross <tc@traviscross.com> 1395665690 +0000
    
    Use the system version of APR / APR-util if possible
    
    Autodetect whether the system libapr / libaprutil has our
    necessary modifications and use it if it does.

As you can see, there are 2 author fields and 1 committer field instead of 1 author and 1 committer. Looks like libgit2 fails on parsing the commit because of this (after `author` it expects `committer` but finds instead another `author`).

### PR DESCRIPTION
**Pull request by carlosmn**
Some tools create multiple author fields. git is rather lax when parsing
them, although fsck does complain about them. This means that they exist
in the wild.

As it's not too taxing to check for them, and there shouldn't be a
noticeable slowdown when dealing with correct commits, add logic to skip
over these extra fields when parsing the commit.

----

The size check may look a bit awkward. It's done this way because we don't have `git__prefixncmp()` and I didn't quite feel this deserved adding more util functions.

This fixes #3182

### CODE REVIEW

File: src/commit.c [hunk 1]
```diff
@@ -337,6 +338,15 @@ int git_commit__parse(void *_commit, git_odb_object *odb_obj)
 	if (git_signature__parse(commit->author, &buffer, buffer_end, "author ", '\n') < 0)
 		return -1;
 
+	/* Some tools create multiple author fields, ignore the extra ones */
+	while ((size_t)(buffer_end - buffer) >= strlen("author ") && !git__prefixcmp(buffer, "author ")) {
+		if (git_signature__parse(&dummy_sig, &buffer, buffer_end, "author ", '\n') < 0)
```
Comment (nulltoken) [inline src/commit.c]: As we ditch those additional fields, should we really fail would the signature be not valid?

Comment (nulltoken) [inline src/commit.c]: Besides, what's the point of even parsing them? Can't we just skip the line?

Comment (carlosmn) [inline src/commit.c]: We still expect it to be well-formed, otherwise it's just an invalid commit. We allow the multiple author fields because git lets them through and these commits exist in the wild, but if it just happens to have "author lalala\n" somewhere in the header, that doesn't mean we should ignore the fact that it's malformed.

Comment (nulltoken) [inline src/commit.c]: You're right. This is off-topic. I'm going to log a dedicated issue.
